In [6]:
import pandas as pd
import seaborn as sns
import sqlite3

In [3]:
df = pd.read_csv('cell-count.csv')

In [5]:
df

,project,subject,condition,age,sex,treatment,response,sample,sample_type,time_from_treatment_start,b_cell,cd8_t_cell,cd4_t_cell,nk_cell,monocyte
0,prj1,sbj000,melanoma,57,M,miraclib,no,sample00000,PBMC,0,10908,24440,20491,13864,23511
1,prj1,sbj000,melanoma,57,M,miraclib,no,sample00001,PBMC,7,6777,19407,33459,18170,23011
2,prj1,sbj000,melanoma,57,M,miraclib,no,sample00002,PBMC,14,9794,22940,24274,17482,18332
3,prj1,sbj001,carcinoma,68,M,miraclib,yes,sample00003,PBMC,0,10081,20271,36157,14041,12610
4,prj1,sbj001,carcinoma,68,M,miraclib,yes,sample00004,PBMC,7,4372,33778,38293,16527,14933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10495,prj3,sbj3498,melanoma,67,M,phauximab,no,sample10495,PBMC,7,9246,35456,23132,12888,22512
10496,prj3,sbj3498,melanoma,67,M,phauximab,no,sample10496,PBMC,14,7930,29513,33316,16100,22533
10497,prj3,sbj3499,healthy,54,M,none,NaN,sample10497,PBMC,0,8646,30656,27328,19274,22154
10498,prj3,sbj3499,healthy,54,M,none,NaN,sample10498,PBMC,7,10199,28842,32158,11271,21695
10499,prj3,sbj3499,healthy,54,M,none,NaN,sample10499,PBMC,14,9258,29100,26769,12895,14396

In [10]:
conn = sqlite3.connect("cell_counts.db")
query = "SELECT * FROM samples"
samples = pd.read_sql_query(query, conn)

In [20]:
df = samples[["sample", "b_cell", "cd8_t_cell", "cd4_t_cell", "nk_cell", "monocyte"]].set_index("sample")

In [22]:
df = df.melt(var_name="population", value_name="count", ignore_index=False)

In [24]:
df["total_count"] = df.groupby("sample")["count"].sum()

In [30]:
df["percentage"] = df["count"] * 100 / df["total_count"]

In [35]:
df = df[["total_count", "population", "count", "percentage"]].sort_values(["sample", "population"])

In [36]:
df

             total_count  population  count  percentage
sample
sample00000        93214      b_cell  10908   11.702105
sample00000        93214  cd4_t_cell  20491   21.982749
sample00000        93214  cd8_t_cell  24440   26.219237
sample00000        93214    monocyte  23511   25.222606
sample00000        93214     nk_cell  13864   14.873302
...                  ...         ...    ...         ...
sample10499        92418      b_cell   9258   10.017529
sample10499        92418  cd4_t_cell  26769   28.965137
sample10499        92418  cd8_t_cell  29100   31.487373
sample10499        92418    monocyte  14396   15.577052
sample10499        92418     nk_cell  12895   13.952910

[52500 rows x 4 columns]